In [135]:
from scipy.signal import get_window
import numpy as np
import pandas as pd

In [136]:
signal = [3,5,8,9,4,8,134,0]

In [137]:
d = len(signal) #longueur du signal
p = 4 #taille fenetre

In [138]:
n_labels = 3
label = np.random.randint(n_labels,size=d)

In [139]:
label

array([2, 2, 2, 1, 0, 0, 1, 1])

In [140]:
window = get_window('boxcar',3)

In [141]:
window

array([ 1.,  1.,  1.])

In [142]:
w = np.zeros((d-p+1,p))
for i in range(d-p+1):
    w[i,:] = signal[i:i+p]
    print(w[i,:])

[ 3.  5.  8.  9.]
[ 5.  8.  9.  4.]
[ 8.  9.  4.  8.]
[   9.    4.    8.  134.]
[   4.    8.  134.    0.]


In [150]:
k = 2 #pas de la fenetre
nk = int(np.floor((d-p+1)/k))+1 #le nombre de fenetres
wk = np.zeros((nk,p)) #matrice des fenetres
labelwk = np.zeros((nk)) #les labels des fenetres
for j in range(nk):
    wk[j,:] = signal[j*k:j*k+p]
    labelwk[j] = np.max(np.argmax(np.bincount(label[j*k:j*k+p])))

In [151]:
labelwk

array([ 2.,  0.,  0.])

In [152]:
label

array([2, 2, 2, 1, 0, 0, 1, 1])

In [153]:
signal

[3, 5, 8, 9, 4, 8, 134, 0]